### ISSUE TITLE
Atlas

### ISSUE THREAD

**Issue by dnmacdon** [brainhack-school2020/ValiquetteVanessa_MouseModelAutism_T2W#2]
Are there open atlases for the automated segmentation that you want to do?

**Comment by ValiquetteVanessa** [comment]
If I am not mistaken the Allen Brain Institute has one available. Here is the link to the CoBrA Lab directory for it: https://github.com/CoBrALab/documentation/wiki/Allen-Brain-Adult-Mouse.
